name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Ajusta la rama según necesites

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Asegúrate de usar una versión compatible de Node.js

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Ajusta el comando según tu configuración de construcción

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSS_1S2024 }}
          projectId: tss-1s2024
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
