name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # o la rama que deseas desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Enable Firebase Experiments
        run: firebase experiments:enable webframeworks

      - name: Set up Google Cloud credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: firebase deploy --only hosting
